version: "2"

services:
  search-php-fpm:
    container_name: php-fpm
    image: quay.io/cashrewards/search-ms:develop

    ports:
      - "9000:9000"

    links:
      - "elasticsearch"
      - "redis"

    env_file:
      - .env

  search-nginx:
    container_name: nginx
    image: nginx
    ports:
     - "80:80"
    links:
     - "search-php-fpm"
    volumes_from:
     - search-php-fpm:ro
        # from search-php-fpm container
        # /etc/nginx/conf.d/default.conf
        # /var/www/html   [ image default = /usr/share/nginx/html ]

  redis:
    container_name: redis
    image: redis


  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports: ['127.0.0.1:9200:9200']
    logging:
      driver: none
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.5.0
    ports: ['127.0.0.1:5601:5601']
    depends_on: ['elasticsearch']
    environment: ['server.host=localhost']
    logging:
      driver: none